mysql:
  image: mysql
  volumes:
    - /var/local/mysql:/var/lib/mysql
  container_name: mysql
  environment:
    - MYSQL_DATABASE=items
    - MYSQL_USER=user1
    - MYSQL_PASSWORD=mypass
    - MYSQL_ROOT_PASSWORD=rootpass
  ports:
    - "30306:3306"

wordpress:
  image: wordpress
  container_name: wordpress
  ports:
    - "90:80"
  links:
    - mysql
